/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntipodasIndexRouteImport } from './routes/antipodas.index'
import { Route as ApiPresenciaRouteImport } from './routes/api/presencia'
import { Route as ApiVisitasRouteImport } from './routes/api/visitas'
import { Route as ContactoIndexRouteImport } from './routes/contacto.index'
import { Route as CotaNRouteImport } from './routes/cota.$n'
import { Route as CotasIndexRouteImport } from './routes/cotas.index'
import { Route as DirigidoIndexRouteImport } from './routes/dirigido.index'
import { Route as LetraIdRouteImport } from './routes/letra.$id'
import { Route as LoopIndexRouteImport } from './routes/loop.index'
import { Route as MiochisIndexRouteImport } from './routes/miochis.index'
import { Route as PeldanoNRouteImport } from './routes/peldano.$n'
import { Route as SeminarioIndexRouteImport } from './routes/seminario.index'
import { Route as SitioIndexRouteImport } from './routes/sitio.index'
import { Route as SuperyaIndexRouteImport } from './routes/superya.index'
import { Route as TeatroIndexRouteImport } from './routes/teatro.index'
import { Route as ApiDiarioIndexRouteImport } from './routes/api/diario.index'
import { Route as ApiDiarioSesionRouteImport } from './routes/api/diario.sesion'
import { Route as DirigidoHizoLugarIndexRouteImport } from './routes/dirigido.hizo-lugar.index'
import { Route as SeminarioEnigmaOjoIndexRouteImport } from './routes/seminario.enigma-ojo.index'
import { Route as ApiDiarioArchivoIdRouteImport } from './routes/api/diario.archivo.$id'
import { Route as SeminarioSesiones01ContingenciaIndexRouteImport } from './routes/seminario.sesiones.01-contingencia.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntipodasIndexRoute = AntipodasIndexRouteImport.update({
  id: '/antipodas/',
  path: '/antipodas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresenciaRoute = ApiPresenciaRouteImport.update({
  id: '/api/presencia',
  path: '/api/presencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitasRoute = ApiVisitasRouteImport.update({
  id: '/api/visitas',
  path: '/api/visitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoIndexRoute = ContactoIndexRouteImport.update({
  id: '/contacto/',
  path: '/contacto/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotaNRoute = CotaNRouteImport.update({
  id: '/cota/$n',
  path: '/cota/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const CotasIndexRoute = CotasIndexRouteImport.update({
  id: '/cotas/',
  path: '/cotas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirigidoIndexRoute = DirigidoIndexRouteImport.update({
  id: '/dirigido/',
  path: '/dirigido/',
  getParentRoute: () => rootRouteImport,
} as any)
const LetraIdRoute = LetraIdRouteImport.update({
  id: '/letra/$id',
  path: '/letra/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopIndexRoute = LoopIndexRouteImport.update({
  id: '/loop/',
  path: '/loop/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiochisIndexRoute = MiochisIndexRouteImport.update({
  id: '/miochis/',
  path: '/miochis/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeldanoNRoute = PeldanoNRouteImport.update({
  id: '/peldano/$n',
  path: '/peldano/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminarioIndexRoute = SeminarioIndexRouteImport.update({
  id: '/seminario/',
  path: '/seminario/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitioIndexRoute = SitioIndexRouteImport.update({
  id: '/sitio/',
  path: '/sitio/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperyaIndexRoute = SuperyaIndexRouteImport.update({
  id: '/superya/',
  path: '/superya/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeatroIndexRoute = TeatroIndexRouteImport.update({
  id: '/teatro/',
  path: '/teatro/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiarioIndexRoute = ApiDiarioIndexRouteImport.update({
  id: '/api/diario/',
  path: '/api/diario/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiarioSesionRoute = ApiDiarioSesionRouteImport.update({
  id: '/api/diario/sesion',
  path: '/api/diario/sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const DirigidoHizoLugarIndexRoute = DirigidoHizoLugarIndexRouteImport.update({
  id: '/dirigido/hizo-lugar/',
  path: '/dirigido/hizo-lugar/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminarioEnigmaOjoIndexRoute = SeminarioEnigmaOjoIndexRouteImport.update({
  id: '/seminario/enigma-ojo/',
  path: '/seminario/enigma-ojo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiarioArchivoIdRoute = ApiDiarioArchivoIdRouteImport.update({
  id: '/api/diario/archivo/$id',
  path: '/api/diario/archivo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminarioSesiones01ContingenciaIndexRoute =
  SeminarioSesiones01ContingenciaIndexRouteImport.update({
    id: '/seminario/sesiones/01-contingencia/',
    path: '/seminario/sesiones/01-contingencia/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/presencia': typeof ApiPresenciaRoute
  '/api/visitas': typeof ApiVisitasRoute
  '/cota/$n': typeof CotaNRoute
  '/letra/$id': typeof LetraIdRoute
  '/peldano/$n': typeof PeldanoNRoute
  '/antipodas/': typeof AntipodasIndexRoute
  '/contacto/': typeof ContactoIndexRoute
  '/cotas/': typeof CotasIndexRoute
  '/dirigido/': typeof DirigidoIndexRoute
  '/loop/': typeof LoopIndexRoute
  '/miochis/': typeof MiochisIndexRoute
  '/seminario/': typeof SeminarioIndexRoute
  '/sitio/': typeof SitioIndexRoute
  '/superya/': typeof SuperyaIndexRoute
  '/teatro/': typeof TeatroIndexRoute
  '/api/diario/sesion': typeof ApiDiarioSesionRoute
  '/api/diario/': typeof ApiDiarioIndexRoute
  '/dirigido/hizo-lugar/': typeof DirigidoHizoLugarIndexRoute
  '/seminario/enigma-ojo/': typeof SeminarioEnigmaOjoIndexRoute
  '/api/diario/archivo/$id': typeof ApiDiarioArchivoIdRoute
  '/seminario/sesiones/01-contingencia/': typeof SeminarioSesiones01ContingenciaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/presencia': typeof ApiPresenciaRoute
  '/api/visitas': typeof ApiVisitasRoute
  '/cota/$n': typeof CotaNRoute
  '/letra/$id': typeof LetraIdRoute
  '/peldano/$n': typeof PeldanoNRoute
  '/antipodas': typeof AntipodasIndexRoute
  '/contacto': typeof ContactoIndexRoute
  '/cotas': typeof CotasIndexRoute
  '/dirigido': typeof DirigidoIndexRoute
  '/loop': typeof LoopIndexRoute
  '/miochis': typeof MiochisIndexRoute
  '/seminario': typeof SeminarioIndexRoute
  '/sitio': typeof SitioIndexRoute
  '/superya': typeof SuperyaIndexRoute
  '/teatro': typeof TeatroIndexRoute
  '/api/diario/sesion': typeof ApiDiarioSesionRoute
  '/api/diario': typeof ApiDiarioIndexRoute
  '/dirigido/hizo-lugar': typeof DirigidoHizoLugarIndexRoute
  '/seminario/enigma-ojo': typeof SeminarioEnigmaOjoIndexRoute
  '/api/diario/archivo/$id': typeof ApiDiarioArchivoIdRoute
  '/seminario/sesiones/01-contingencia': typeof SeminarioSesiones01ContingenciaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/presencia': typeof ApiPresenciaRoute
  '/api/visitas': typeof ApiVisitasRoute
  '/cota/$n': typeof CotaNRoute
  '/letra/$id': typeof LetraIdRoute
  '/peldano/$n': typeof PeldanoNRoute
  '/antipodas/': typeof AntipodasIndexRoute
  '/contacto/': typeof ContactoIndexRoute
  '/cotas/': typeof CotasIndexRoute
  '/dirigido/': typeof DirigidoIndexRoute
  '/loop/': typeof LoopIndexRoute
  '/miochis/': typeof MiochisIndexRoute
  '/seminario/': typeof SeminarioIndexRoute
  '/sitio/': typeof SitioIndexRoute
  '/superya/': typeof SuperyaIndexRoute
  '/teatro/': typeof TeatroIndexRoute
  '/api/diario/sesion': typeof ApiDiarioSesionRoute
  '/api/diario/': typeof ApiDiarioIndexRoute
  '/dirigido/hizo-lugar/': typeof DirigidoHizoLugarIndexRoute
  '/seminario/enigma-ojo/': typeof SeminarioEnigmaOjoIndexRoute
  '/api/diario/archivo/$id': typeof ApiDiarioArchivoIdRoute
  '/seminario/sesiones/01-contingencia/': typeof SeminarioSesiones01ContingenciaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/presencia'
    | '/api/visitas'
    | '/cota/$n'
    | '/letra/$id'
    | '/peldano/$n'
    | '/antipodas/'
    | '/contacto/'
    | '/cotas/'
    | '/dirigido/'
    | '/loop/'
    | '/miochis/'
    | '/seminario/'
    | '/sitio/'
    | '/superya/'
    | '/teatro/'
    | '/api/diario/sesion'
    | '/api/diario/'
    | '/dirigido/hizo-lugar/'
    | '/seminario/enigma-ojo/'
    | '/api/diario/archivo/$id'
    | '/seminario/sesiones/01-contingencia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/presencia'
    | '/api/visitas'
    | '/cota/$n'
    | '/letra/$id'
    | '/peldano/$n'
    | '/antipodas'
    | '/contacto'
    | '/cotas'
    | '/dirigido'
    | '/loop'
    | '/miochis'
    | '/seminario'
    | '/sitio'
    | '/superya'
    | '/teatro'
    | '/api/diario/sesion'
    | '/api/diario'
    | '/dirigido/hizo-lugar'
    | '/seminario/enigma-ojo'
    | '/api/diario/archivo/$id'
    | '/seminario/sesiones/01-contingencia'
  id:
    | '__root__'
    | '/'
    | '/api/presencia'
    | '/api/visitas'
    | '/cota/$n'
    | '/letra/$id'
    | '/peldano/$n'
    | '/antipodas/'
    | '/contacto/'
    | '/cotas/'
    | '/dirigido/'
    | '/loop/'
    | '/miochis/'
    | '/seminario/'
    | '/sitio/'
    | '/superya/'
    | '/teatro/'
    | '/api/diario/sesion'
    | '/api/diario/'
    | '/dirigido/hizo-lugar/'
    | '/seminario/enigma-ojo/'
    | '/api/diario/archivo/$id'
    | '/seminario/sesiones/01-contingencia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPresenciaRoute: typeof ApiPresenciaRoute
  ApiVisitasRoute: typeof ApiVisitasRoute
  CotaNRoute: typeof CotaNRoute
  LetraIdRoute: typeof LetraIdRoute
  PeldanoNRoute: typeof PeldanoNRoute
  AntipodasIndexRoute: typeof AntipodasIndexRoute
  ContactoIndexRoute: typeof ContactoIndexRoute
  CotasIndexRoute: typeof CotasIndexRoute
  DirigidoIndexRoute: typeof DirigidoIndexRoute
  LoopIndexRoute: typeof LoopIndexRoute
  MiochisIndexRoute: typeof MiochisIndexRoute
  SeminarioIndexRoute: typeof SeminarioIndexRoute
  SitioIndexRoute: typeof SitioIndexRoute
  SuperyaIndexRoute: typeof SuperyaIndexRoute
  TeatroIndexRoute: typeof TeatroIndexRoute
  ApiDiarioSesionRoute: typeof ApiDiarioSesionRoute
  ApiDiarioIndexRoute: typeof ApiDiarioIndexRoute
  DirigidoHizoLugarIndexRoute: typeof DirigidoHizoLugarIndexRoute
  SeminarioEnigmaOjoIndexRoute: typeof SeminarioEnigmaOjoIndexRoute
  ApiDiarioArchivoIdRoute: typeof ApiDiarioArchivoIdRoute
  SeminarioSesiones01ContingenciaIndexRoute: typeof SeminarioSesiones01ContingenciaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antipodas/': {
      id: '/antipodas/'
      path: '/antipodas'
      fullPath: '/antipodas/'
      preLoaderRoute: typeof AntipodasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presencia': {
      id: '/api/presencia'
      path: '/api/presencia'
      fullPath: '/api/presencia'
      preLoaderRoute: typeof ApiPresenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visitas': {
      id: '/api/visitas'
      path: '/api/visitas'
      fullPath: '/api/visitas'
      preLoaderRoute: typeof ApiVisitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto/': {
      id: '/contacto/'
      path: '/contacto'
      fullPath: '/contacto/'
      preLoaderRoute: typeof ContactoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cota/$n': {
      id: '/cota/$n'
      path: '/cota/$n'
      fullPath: '/cota/$n'
      preLoaderRoute: typeof CotaNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotas/': {
      id: '/cotas/'
      path: '/cotas'
      fullPath: '/cotas/'
      preLoaderRoute: typeof CotasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dirigido/': {
      id: '/dirigido/'
      path: '/dirigido'
      fullPath: '/dirigido/'
      preLoaderRoute: typeof DirigidoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letra/$id': {
      id: '/letra/$id'
      path: '/letra/$id'
      fullPath: '/letra/$id'
      preLoaderRoute: typeof LetraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loop/': {
      id: '/loop/'
      path: '/loop'
      fullPath: '/loop/'
      preLoaderRoute: typeof LoopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miochis/': {
      id: '/miochis/'
      path: '/miochis'
      fullPath: '/miochis/'
      preLoaderRoute: typeof MiochisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peldano/$n': {
      id: '/peldano/$n'
      path: '/peldano/$n'
      fullPath: '/peldano/$n'
      preLoaderRoute: typeof PeldanoNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminario/': {
      id: '/seminario/'
      path: '/seminario'
      fullPath: '/seminario/'
      preLoaderRoute: typeof SeminarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitio/': {
      id: '/sitio/'
      path: '/sitio'
      fullPath: '/sitio/'
      preLoaderRoute: typeof SitioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superya/': {
      id: '/superya/'
      path: '/superya'
      fullPath: '/superya/'
      preLoaderRoute: typeof SuperyaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teatro/': {
      id: '/teatro/'
      path: '/teatro'
      fullPath: '/teatro/'
      preLoaderRoute: typeof TeatroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diario/': {
      id: '/api/diario/'
      path: '/api/diario'
      fullPath: '/api/diario/'
      preLoaderRoute: typeof ApiDiarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diario/sesion': {
      id: '/api/diario/sesion'
      path: '/api/diario/sesion'
      fullPath: '/api/diario/sesion'
      preLoaderRoute: typeof ApiDiarioSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dirigido/hizo-lugar/': {
      id: '/dirigido/hizo-lugar/'
      path: '/dirigido/hizo-lugar'
      fullPath: '/dirigido/hizo-lugar/'
      preLoaderRoute: typeof DirigidoHizoLugarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminario/enigma-ojo/': {
      id: '/seminario/enigma-ojo/'
      path: '/seminario/enigma-ojo'
      fullPath: '/seminario/enigma-ojo/'
      preLoaderRoute: typeof SeminarioEnigmaOjoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diario/archivo/$id': {
      id: '/api/diario/archivo/$id'
      path: '/api/diario/archivo/$id'
      fullPath: '/api/diario/archivo/$id'
      preLoaderRoute: typeof ApiDiarioArchivoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminario/sesiones/01-contingencia/': {
      id: '/seminario/sesiones/01-contingencia/'
      path: '/seminario/sesiones/01-contingencia'
      fullPath: '/seminario/sesiones/01-contingencia/'
      preLoaderRoute: typeof SeminarioSesiones01ContingenciaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPresenciaRoute: ApiPresenciaRoute,
  ApiVisitasRoute: ApiVisitasRoute,
  CotaNRoute: CotaNRoute,
  LetraIdRoute: LetraIdRoute,
  PeldanoNRoute: PeldanoNRoute,
  AntipodasIndexRoute: AntipodasIndexRoute,
  ContactoIndexRoute: ContactoIndexRoute,
  CotasIndexRoute: CotasIndexRoute,
  DirigidoIndexRoute: DirigidoIndexRoute,
  LoopIndexRoute: LoopIndexRoute,
  MiochisIndexRoute: MiochisIndexRoute,
  SeminarioIndexRoute: SeminarioIndexRoute,
  SitioIndexRoute: SitioIndexRoute,
  SuperyaIndexRoute: SuperyaIndexRoute,
  TeatroIndexRoute: TeatroIndexRoute,
  ApiDiarioSesionRoute: ApiDiarioSesionRoute,
  ApiDiarioIndexRoute: ApiDiarioIndexRoute,
  DirigidoHizoLugarIndexRoute: DirigidoHizoLugarIndexRoute,
  SeminarioEnigmaOjoIndexRoute: SeminarioEnigmaOjoIndexRoute,
  ApiDiarioArchivoIdRoute: ApiDiarioArchivoIdRoute,
  SeminarioSesiones01ContingenciaIndexRoute:
    SeminarioSesiones01ContingenciaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
